<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite hostname="DESKTOP-FEJVQKG" ignored="0" name="Default test" tests="2" failures="1" timestamp="2022-01-28T13:24:54 IST" time="63.68" errors="0">
  <testcase name="TC04_COM_LoginFunctionality" time="13.467" classname="com.perfaware.automation.oms.sterling.common.testcases.COM_LoginFunctionality">
    <skipped/>
  </testcase> <!-- TC04_COM_LoginFunctionality -->
  <testcase name="TC04_COM_LoginFunctionality" time="12.479" classname="com.perfaware.automation.oms.sterling.common.testcases.COM_LoginFunctionality">
    <failure type="java.lang.AssertionError" message="expected [Invalid Credentials passed. Please try again...] but found [The combination of user name and password you entered does not match any existing accounts. Please try again.]">
      <![CDATA[java.lang.AssertionError: expected [Invalid Credentials passed. Please try again...] but found [The combination of user name and password you entered does not match any existing accounts. Please try again.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.perfaware.automation.oms.sterling.common.com.pageobjects.Page_COM_Login.captureLoginError(Page_COM_Login.java:71)
at com.perfaware.automation.oms.sterling.common.testcases.COM_LoginFunctionality.TC04_COM_LoginFunctionality(COM_LoginFunctionality.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC04_COM_LoginFunctionality -->
=======
<testsuite hostname="DESKTOP-TV3IFO6" ignored="0" name="Default test" tests="1" failures="0" timestamp="2022-01-28T14:33:16 IST" time="13.912" errors="0">
  <testcase name="testApi" time="13.591" classname="com.perfaware.automation.oms.sterling.common.testcases.test"/>
>>>>>>> dcc5674b1d688ec4edd42313b0c0c11b8897bb43
</testsuite> <!-- Default test -->
