<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-FEJVQKG" name="com.perfaware.automation.oms.sterling.common.testcases.COM_LoginFunctionality" tests="2" failures="1" timestamp="2022-01-18T23:57:47 IST" time="62.572" errors="0">
  <testcase name="TC05_COM_LoginFunctionality" time="37.198" classname="com.perfaware.automation.oms.sterling.common.testcases.COM_LoginFunctionality">
    <failure type="java.lang.AssertionError" message="expected [Invalid Credentials passed. Please try again...] but found [The combination of user name and password you entered does not match any existing accounts. Please try again.]">
      <![CDATA[java.lang.AssertionError: expected [Invalid Credentials passed. Please try again...] but found [The combination of user name and password you entered does not match any existing accounts. Please try again.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.perfaware.automation.oms.sterling.common.com.pageobjects.Page_COM_Login.captureLoginError(Page_COM_Login.java:72)
at com.perfaware.automation.oms.sterling.common.testcases.COM_LoginFunctionality.TC05_COM_LoginFunctionality(COM_LoginFunctionality.java:92)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- TC05_COM_LoginFunctionality -->
  <system-out/>
  <testcase name="TC05_COM_LoginFunctionality" time="25.374" classname="com.perfaware.automation.oms.sterling.common.testcases.COM_LoginFunctionality">
    <skipped/>
  </testcase> <!-- TC05_COM_LoginFunctionality -->
  <system-out/>
</testsuite> <!-- com.perfaware.automation.oms.sterling.common.testcases.COM_LoginFunctionality -->
